// File is generated by gobind. Do not edit.

#include <jni.h>
#include "seq.h"
#include "classes.h"


void init_proxies() {
	JNIEnv *env = go_seq_push_local_frame(0);
	jclass clazz;
	go_seq_pop_local_frame(env);
}

