// JNI function headers for the Go <=> Java bridge.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.

#ifndef __Holochain_H__
#define __Holochain_H__

#include <jni.h>

extern jclass proxy_class_holochain_Action;
extern jmethodID proxy_class_holochain_Action_cons;

// skipped method Action.Args with unsupported parameter or return types

// skipped method Action.Do with unsupported parameter or return types

nstring cproxyholochain_Action_Name(int32_t refnum);

// skipped method Action.Receive with unsupported parameter or return types

extern jclass proxy_class_holochain_Agent;
extern jmethodID proxy_class_holochain_Agent_cons;

// skipped method Agent.AgentEntry with unsupported parameter or return types

// skipped method Agent.AgentType with unsupported parameter or return types

// skipped method Agent.GenKeys with unsupported parameter or return types

// skipped method Agent.Identity with unsupported parameter or return types

// skipped method Agent.NodeID with unsupported parameter or return types

// skipped method Agent.PrivKey with unsupported parameter or return types

// skipped method Agent.PubKey with unsupported parameter or return types

// skipped method Agent.SetIdentity with unsupported parameter or return types

extern jclass proxy_class_holochain_ArgsAction;
extern jmethodID proxy_class_holochain_ArgsAction_cons;

// skipped method ArgsAction.Args with unsupported parameter or return types

// skipped method ArgsAction.Do with unsupported parameter or return types

extern jclass proxy_class_holochain_CommittingAction;
extern jmethodID proxy_class_holochain_CommittingAction_cons;

// skipped method CommittingAction.Args with unsupported parameter or return types

int32_t cproxyholochain_CommittingAction_CheckValidationRequest(int32_t refnum, int32_t def);

// skipped method CommittingAction.Do with unsupported parameter or return types

int32_t cproxyholochain_CommittingAction_Entry(int32_t refnum);

nstring cproxyholochain_CommittingAction_EntryType(int32_t refnum);

nstring cproxyholochain_CommittingAction_Name(int32_t refnum);

// skipped method CommittingAction.Receive with unsupported parameter or return types

void cproxyholochain_CommittingAction_SetHeader(int32_t refnum, int32_t header);

// skipped method CommittingAction.SysValidation with unsupported parameter or return types

extern jclass proxy_class_holochain_Entry;
extern jmethodID proxy_class_holochain_Entry_cons;

// skipped method Entry.Content with unsupported parameter or return types

typedef struct cproxyholochain_Entry_Marshal_return {
    nbyteslice r0;
    int32_t r1;
} cproxyholochain_Entry_Marshal_return;
struct cproxyholochain_Entry_Marshal_return cproxyholochain_Entry_Marshal(int32_t refnum);

// skipped method Entry.Sum with unsupported parameter or return types

int32_t cproxyholochain_Entry_Unmarshal(int32_t refnum, nbyteslice p0);

extern jclass proxy_class_holochain_Revocation;
extern jmethodID proxy_class_holochain_Revocation_cons;

typedef struct cproxyholochain_Revocation_Marshal_return {
    nbyteslice r0;
    int32_t r1;
} cproxyholochain_Revocation_Marshal_return;
struct cproxyholochain_Revocation_Marshal_return cproxyholochain_Revocation_Marshal(int32_t refnum);

int32_t cproxyholochain_Revocation_Unmarshal(int32_t refnum, nbyteslice p0);

int32_t cproxyholochain_Revocation_Verify(int32_t refnum);

extern jclass proxy_class_holochain_Ribosome;
extern jmethodID proxy_class_holochain_Ribosome_cons;

// skipped method Ribosome.BridgeGenesis with unsupported parameter or return types

// skipped method Ribosome.Call with unsupported parameter or return types

int32_t cproxyholochain_Ribosome_ChainGenesis(int32_t refnum);

typedef struct cproxyholochain_Ribosome_Receive_return {
    nstring r0;
    int32_t r1;
} cproxyholochain_Ribosome_Receive_return;
struct cproxyholochain_Ribosome_Receive_return cproxyholochain_Ribosome_Receive(int32_t refnum, nstring from, nstring msg);

// skipped method Ribosome.Run with unsupported parameter or return types

// skipped method Ribosome.RunAsyncSendResponse with unsupported parameter or return types

nstring cproxyholochain_Ribosome_Type(int32_t refnum);

// skipped method Ribosome.ValidateAction with unsupported parameter or return types

// skipped method Ribosome.ValidatePackagingRequest with unsupported parameter or return types

extern jclass proxy_class_holochain_SchemaValidator;
extern jmethodID proxy_class_holochain_SchemaValidator_cons;

// skipped method SchemaValidator.Validate with unsupported parameter or return types

extern jclass proxy_class_holochain_ValidatingAction;
extern jmethodID proxy_class_holochain_ValidatingAction_cons;

// skipped method ValidatingAction.Args with unsupported parameter or return types

int32_t cproxyholochain_ValidatingAction_CheckValidationRequest(int32_t refnum, int32_t def);

// skipped method ValidatingAction.Do with unsupported parameter or return types

nstring cproxyholochain_ValidatingAction_Name(int32_t refnum);

// skipped method ValidatingAction.Receive with unsupported parameter or return types

// skipped method ValidatingAction.SysValidation with unsupported parameter or return types

extern jclass proxy_class_holochain_Warrant;
extern jmethodID proxy_class_holochain_Warrant_cons;

int32_t cproxyholochain_Warrant_Decode(int32_t refnum, nbyteslice data);

typedef struct cproxyholochain_Warrant_Encode_return {
    nbyteslice r0;
    int32_t r1;
} cproxyholochain_Warrant_Encode_return;
struct cproxyholochain_Warrant_Encode_return cproxyholochain_Warrant_Encode(int32_t refnum);

// skipped method Warrant.Parties with unsupported parameter or return types

// skipped method Warrant.Property with unsupported parameter or return types

nint cproxyholochain_Warrant_Type(int32_t refnum);

int32_t cproxyholochain_Warrant_Verify(int32_t refnum, int32_t h);

extern jclass proxy_class_holochain_ActionBridge;
extern jmethodID proxy_class_holochain_ActionBridge_cons;
extern jclass proxy_class_holochain_ActionCall;
extern jmethodID proxy_class_holochain_ActionCall_cons;
extern jclass proxy_class_holochain_ActionCommit;
extern jmethodID proxy_class_holochain_ActionCommit_cons;
extern jclass proxy_class_holochain_ActionDebug;
extern jmethodID proxy_class_holochain_ActionDebug_cons;
extern jclass proxy_class_holochain_ActionDel;
extern jmethodID proxy_class_holochain_ActionDel_cons;
extern jclass proxy_class_holochain_ActionGet;
extern jmethodID proxy_class_holochain_ActionGet_cons;
extern jclass proxy_class_holochain_ActionGetBridges;
extern jmethodID proxy_class_holochain_ActionGetBridges_cons;
extern jclass proxy_class_holochain_ActionGetLinks;
extern jmethodID proxy_class_holochain_ActionGetLinks_cons;
extern jclass proxy_class_holochain_ActionLink;
extern jmethodID proxy_class_holochain_ActionLink_cons;
extern jclass proxy_class_holochain_ActionListAdd;
extern jmethodID proxy_class_holochain_ActionListAdd_cons;
extern jclass proxy_class_holochain_ActionMakeHash;
extern jmethodID proxy_class_holochain_ActionMakeHash_cons;
extern jclass proxy_class_holochain_ActionMod;
extern jmethodID proxy_class_holochain_ActionMod_cons;
extern jclass proxy_class_holochain_ActionModAgent;
extern jmethodID proxy_class_holochain_ActionModAgent_cons;
extern jclass proxy_class_holochain_ActionProperty;
extern jmethodID proxy_class_holochain_ActionProperty_cons;
extern jclass proxy_class_holochain_ActionPut;
extern jmethodID proxy_class_holochain_ActionPut_cons;
extern jclass proxy_class_holochain_ActionQuery;
extern jmethodID proxy_class_holochain_ActionQuery_cons;
extern jclass proxy_class_holochain_ActionSend;
extern jmethodID proxy_class_holochain_ActionSend_cons;
extern jclass proxy_class_holochain_ActionSign;
extern jmethodID proxy_class_holochain_ActionSign_cons;
extern jclass proxy_class_holochain_ActionVerifySignature;
extern jmethodID proxy_class_holochain_ActionVerifySignature_cons;
extern jclass proxy_class_holochain_AgentEntry;
extern jmethodID proxy_class_holochain_AgentEntry_cons;
extern jclass proxy_class_holochain_AgentFixture;
extern jmethodID proxy_class_holochain_AgentFixture_cons;
extern jclass proxy_class_holochain_AppMsg;
extern jmethodID proxy_class_holochain_AppMsg_cons;
extern jclass proxy_class_holochain_AppPackage;
extern jmethodID proxy_class_holochain_AppPackage_cons;
extern jclass proxy_class_holochain_AppPackageScenario;
extern jmethodID proxy_class_holochain_AppPackageScenario_cons;
extern jclass proxy_class_holochain_AppPackageTests;
extern jmethodID proxy_class_holochain_AppPackageTests_cons;
extern jclass proxy_class_holochain_AppPackageUIFile;
extern jmethodID proxy_class_holochain_AppPackageUIFile_cons;
extern jclass proxy_class_holochain_Arg;
extern jmethodID proxy_class_holochain_Arg_cons;
extern jclass proxy_class_holochain_BSReq;
extern jmethodID proxy_class_holochain_BSReq_cons;
extern jclass proxy_class_holochain_BSResp;
extern jmethodID proxy_class_holochain_BSResp_cons;
extern jclass proxy_class_holochain_Bridge;
extern jmethodID proxy_class_holochain_Bridge_cons;
extern jclass proxy_class_holochain_BridgeApp;
extern jmethodID proxy_class_holochain_BridgeApp_cons;
extern jclass proxy_class_holochain_Bucket;
extern jmethodID proxy_class_holochain_Bucket_cons;
extern jclass proxy_class_holochain_BytesSent;
extern jmethodID proxy_class_holochain_BytesSent_cons;
extern jclass proxy_class_holochain_Callback;
extern jmethodID proxy_class_holochain_Callback_cons;
extern jclass proxy_class_holochain_Capability;
extern jmethodID proxy_class_holochain_Capability_cons;
extern jclass proxy_class_holochain_Chain;
extern jmethodID proxy_class_holochain_Chain_cons;
extern jclass proxy_class_holochain_ChainPair;
extern jmethodID proxy_class_holochain_ChainPair_cons;
extern jclass proxy_class_holochain_Change;
extern jmethodID proxy_class_holochain_Change_cons;
extern jclass proxy_class_holochain_CloneSpec;
extern jmethodID proxy_class_holochain_CloneSpec_cons;
extern jclass proxy_class_holochain_CloserPeersResp;
extern jmethodID proxy_class_holochain_CloserPeersResp_cons;
extern jclass proxy_class_holochain_Config;
extern jmethodID proxy_class_holochain_Config_cons;
extern jclass proxy_class_holochain_DHT;
extern jmethodID proxy_class_holochain_DHT_cons;
extern jclass proxy_class_holochain_DHTConfig;
extern jmethodID proxy_class_holochain_DHTConfig_cons;
extern jclass proxy_class_holochain_DNA;
extern jmethodID proxy_class_holochain_DNA_cons;
extern jclass proxy_class_holochain_DNAFile;
extern jmethodID proxy_class_holochain_DNAFile_cons;
extern jclass proxy_class_holochain_DelEntry;
extern jmethodID proxy_class_holochain_DelEntry_cons;
extern jclass proxy_class_holochain_DelReq;
extern jmethodID proxy_class_holochain_DelReq_cons;
extern jclass proxy_class_holochain_EntryDef;
extern jmethodID proxy_class_holochain_EntryDef_cons;
extern jclass proxy_class_holochain_EntryDefFile;
extern jmethodID proxy_class_holochain_EntryDefFile_cons;
extern jclass proxy_class_holochain_ErrorResponse;
extern jmethodID proxy_class_holochain_ErrorResponse_cons;
extern jclass proxy_class_holochain_FindNodeReq;
extern jmethodID proxy_class_holochain_FindNodeReq_cons;
extern jclass proxy_class_holochain_FunctionDef;
extern jmethodID proxy_class_holochain_FunctionDef_cons;
extern jclass proxy_class_holochain_GetLinksOptions;
extern jmethodID proxy_class_holochain_GetLinksOptions_cons;
extern jclass proxy_class_holochain_GetOptions;
extern jmethodID proxy_class_holochain_GetOptions_cons;
extern jclass proxy_class_holochain_GetReq;
extern jmethodID proxy_class_holochain_GetReq_cons;
extern jclass proxy_class_holochain_GetResp;
extern jmethodID proxy_class_holochain_GetResp_cons;
extern jclass proxy_class_holochain_GobEntry;
extern jmethodID proxy_class_holochain_GobEntry_cons;
extern jclass proxy_class_holochain_Gossip;
extern jmethodID proxy_class_holochain_Gossip_cons;
extern jclass proxy_class_holochain_GossipReq;
extern jmethodID proxy_class_holochain_GossipReq_cons;
extern jclass proxy_class_holochain_Header;
extern jmethodID proxy_class_holochain_Header_cons;
extern jclass proxy_class_holochain_Holochain;
extern jmethodID proxy_class_holochain_Holochain_cons;
extern jclass proxy_class_holochain_JSONEntry;
extern jmethodID proxy_class_holochain_JSONEntry_cons;
extern jclass proxy_class_holochain_JSONSchemaValidator;
extern jmethodID proxy_class_holochain_JSONSchemaValidator_cons;
extern jclass proxy_class_holochain_JSRibosome;
extern jmethodID proxy_class_holochain_JSRibosome_cons;
extern jclass proxy_class_holochain_LibP2PAgent;
extern jmethodID proxy_class_holochain_LibP2PAgent_cons;
extern jclass proxy_class_holochain_Link;
extern jmethodID proxy_class_holochain_Link_cons;
extern jclass proxy_class_holochain_LinkEvent;
extern jmethodID proxy_class_holochain_LinkEvent_cons;
extern jclass proxy_class_holochain_LinkQuery;
extern jmethodID proxy_class_holochain_LinkQuery_cons;
extern jclass proxy_class_holochain_LinkQueryResp;
extern jmethodID proxy_class_holochain_LinkQueryResp_cons;
extern jclass proxy_class_holochain_LinkReq;
extern jmethodID proxy_class_holochain_LinkReq_cons;
extern jclass proxy_class_holochain_LinksEntry;
extern jmethodID proxy_class_holochain_LinksEntry_cons;
extern jclass proxy_class_holochain_ListAddReq;
extern jmethodID proxy_class_holochain_ListAddReq_cons;
extern jclass proxy_class_holochain_Logger;
extern jmethodID proxy_class_holochain_Logger_cons;
extern jclass proxy_class_holochain_Loggers;
extern jmethodID proxy_class_holochain_Loggers_cons;
extern jclass proxy_class_holochain_Message;
extern jmethodID proxy_class_holochain_Message_cons;
extern jclass proxy_class_holochain_Meta;
extern jmethodID proxy_class_holochain_Meta_cons;
extern jclass proxy_class_holochain_ModAgentOptions;
extern jmethodID proxy_class_holochain_ModAgentOptions_cons;
extern jclass proxy_class_holochain_ModReq;
extern jmethodID proxy_class_holochain_ModReq_cons;
extern jclass proxy_class_holochain_Node;
extern jmethodID proxy_class_holochain_Node_cons;
extern jclass proxy_class_holochain_Nucleus;
extern jmethodID proxy_class_holochain_Nucleus_cons;
extern jclass proxy_class_holochain_Package;
extern jmethodID proxy_class_holochain_Package_cons;
extern jclass proxy_class_holochain_PeerInfo;
extern jmethodID proxy_class_holochain_PeerInfo_cons;
extern jclass proxy_class_holochain_PeerList;
extern jmethodID proxy_class_holochain_PeerList_cons;
extern jclass proxy_class_holochain_PeerRecord;
extern jmethodID proxy_class_holochain_PeerRecord_cons;
extern jclass proxy_class_holochain_Progenitor;
extern jmethodID proxy_class_holochain_Progenitor_cons;
extern jclass proxy_class_holochain_Protocol;
extern jmethodID proxy_class_holochain_Protocol_cons;
extern jclass proxy_class_holochain_Put;
extern jmethodID proxy_class_holochain_Put_cons;
extern jclass proxy_class_holochain_PutReq;
extern jmethodID proxy_class_holochain_PutReq_cons;
extern jclass proxy_class_holochain_QueryConstrain;
extern jmethodID proxy_class_holochain_QueryConstrain_cons;
extern jclass proxy_class_holochain_QueryOptions;
extern jmethodID proxy_class_holochain_QueryOptions_cons;
extern jclass proxy_class_holochain_QueryOrder;
extern jmethodID proxy_class_holochain_QueryOrder_cons;
extern jclass proxy_class_holochain_QueryResult;
extern jmethodID proxy_class_holochain_QueryResult_cons;
extern jclass proxy_class_holochain_QueryReturn;
extern jmethodID proxy_class_holochain_QueryReturn_cons;
extern jclass proxy_class_holochain_RoutingTable;
extern jmethodID proxy_class_holochain_RoutingTable_cons;
extern jclass proxy_class_holochain_SelfRevocation;
extern jmethodID proxy_class_holochain_SelfRevocation_cons;
extern jclass proxy_class_holochain_SelfRevocationWarrant;
extern jmethodID proxy_class_holochain_SelfRevocationWarrant_cons;
extern jclass proxy_class_holochain_SendOptions;
extern jmethodID proxy_class_holochain_SendOptions_cons;
extern jclass proxy_class_holochain_Service;
extern jmethodID proxy_class_holochain_Service_cons;
extern jclass proxy_class_holochain_ServiceConfig;
extern jmethodID proxy_class_holochain_ServiceConfig_cons;
extern jclass proxy_class_holochain_Signature;
extern jmethodID proxy_class_holochain_Signature_cons;
extern jclass proxy_class_holochain_StatusChange;
extern jmethodID proxy_class_holochain_StatusChange_cons;
extern jclass proxy_class_holochain_TaggedHash;
extern jmethodID proxy_class_holochain_TaggedHash_cons;
extern jclass proxy_class_holochain_TestConfig;
extern jmethodID proxy_class_holochain_TestConfig_cons;
extern jclass proxy_class_holochain_TestData;
extern jmethodID proxy_class_holochain_TestData_cons;
extern jclass proxy_class_holochain_TestFixtures;
extern jmethodID proxy_class_holochain_TestFixtures_cons;
extern jclass proxy_class_holochain_TestSet;
extern jmethodID proxy_class_holochain_TestSet_cons;
extern jclass proxy_class_holochain_ValidateQuery;
extern jmethodID proxy_class_holochain_ValidateQuery_cons;
extern jclass proxy_class_holochain_ValidateResponse;
extern jmethodID proxy_class_holochain_ValidateResponse_cons;
extern jclass proxy_class_holochain_ValidationPackage;
extern jmethodID proxy_class_holochain_ValidationPackage_cons;
extern jclass proxy_class_holochain_Zome;
extern jmethodID proxy_class_holochain_Zome_cons;
extern jclass proxy_class_holochain_ZomeFile;
extern jmethodID proxy_class_holochain_ZomeFile_cons;
extern jclass proxy_class_holochain_ZygoRibosome;
extern jmethodID proxy_class_holochain_ZygoRibosome_cons;
#endif
