// Java class holochain.ActionModAgent is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class ActionModAgent implements Seq.Proxy, ArgsAction {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    ActionModAgent(Seq.Ref ref) { this.ref = ref; }
    
    public ActionModAgent() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field ActionModAgent.Identity with unsupported type: *types.Named
    
    public final native String getRevocation();
    public final native void setRevocation(String v);
    
    // skipped method ActionModAgent.Args with unsupported parameter or return types
    
    // skipped method ActionModAgent.Do with unsupported parameter or return types
    
    public native String name();
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof ActionModAgent)) {
            return false;
        }
        ActionModAgent that = (ActionModAgent)o;
        // skipped field ActionModAgent.Identity with unsupported type: *types.Named
        
        String thisRevocation = getRevocation();
        String thatRevocation = that.getRevocation();
        if (thisRevocation == null) {
            if (thatRevocation != null) {
                return false;
            }
        } else if (!thisRevocation.equals(thatRevocation)) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getRevocation()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("ActionModAgent").append("{");
        b.append("Revocation:").append(getRevocation()).append(",");
        return b.append("}").toString();
    }
}

