// Java class holochain.ActionDel is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class ActionDel implements Seq.Proxy, Action, ArgsAction, CommittingAction, ValidatingAction {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    ActionDel(Seq.Ref ref) { this.ref = ref; }
    
    public ActionDel() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped method ActionDel.Args with unsupported parameter or return types
    
    public native void checkValidationRequest(EntryDef def) throws Exception;
    // skipped method ActionDel.Do with unsupported parameter or return types
    
    public native Entry entry();
    public native String entryType();
    public native String name();
    // skipped method ActionDel.Receive with unsupported parameter or return types
    
    public native void setHeader(Header header);
    // skipped method ActionDel.SysValidation with unsupported parameter or return types
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof ActionDel)) {
            return false;
        }
        ActionDel that = (ActionDel)o;
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("ActionDel").append("{");
        return b.append("}").toString();
    }
}

