// Java class holochain.ActionGetLinks is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class ActionGetLinks implements Seq.Proxy, Action, ArgsAction {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    ActionGetLinks(Seq.Ref ref) { this.ref = ref; }
    
    public ActionGetLinks() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped method ActionGetLinks.Args with unsupported parameter or return types
    
    // skipped method ActionGetLinks.Do with unsupported parameter or return types
    
    public native String name();
    // skipped method ActionGetLinks.Receive with unsupported parameter or return types
    
    // skipped method ActionGetLinks.SysValidation with unsupported parameter or return types
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof ActionGetLinks)) {
            return false;
        }
        ActionGetLinks that = (ActionGetLinks)o;
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("ActionGetLinks").append("{");
        return b.append("}").toString();
    }
}

