// Java class holochain.ActionMod is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class ActionMod implements Seq.Proxy, Action, ArgsAction, CommittingAction, ValidatingAction {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    ActionMod(Seq.Ref ref) { this.ref = ref; }
    
    public ActionMod() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped method ActionMod.Args with unsupported parameter or return types
    
    public native void checkValidationRequest(EntryDef def) throws Exception;
    // skipped method ActionMod.Do with unsupported parameter or return types
    
    public native Entry entry();
    public native String entryType();
    public native String name();
    // skipped method ActionMod.Receive with unsupported parameter or return types
    
    public native void setHeader(Header header);
    // skipped method ActionMod.SysValidation with unsupported parameter or return types
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof ActionMod)) {
            return false;
        }
        ActionMod that = (ActionMod)o;
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("ActionMod").append("{");
        return b.append("}").toString();
    }
}

