// Java class holochain.ActionProperty is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class ActionProperty implements Seq.Proxy, ArgsAction {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    ActionProperty(Seq.Ref ref) { this.ref = ref; }
    
    public ActionProperty() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped method ActionProperty.Args with unsupported parameter or return types
    
    // skipped method ActionProperty.Do with unsupported parameter or return types
    
    public native String name();
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof ActionProperty)) {
            return false;
        }
        ActionProperty that = (ActionProperty)o;
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("ActionProperty").append("{");
        return b.append("}").toString();
    }
}

