// Java class holochain.ActionPut is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class ActionPut implements Seq.Proxy, Action, ArgsAction, ValidatingAction {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    ActionPut(Seq.Ref ref) { this.ref = ref; }
    
    public ActionPut() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped method ActionPut.Args with unsupported parameter or return types
    
    public native void checkValidationRequest(EntryDef def) throws Exception;
    // skipped method ActionPut.Do with unsupported parameter or return types
    
    public native String name();
    // skipped method ActionPut.Receive with unsupported parameter or return types
    
    // skipped method ActionPut.SysValidation with unsupported parameter or return types
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof ActionPut)) {
            return false;
        }
        ActionPut that = (ActionPut)o;
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("ActionPut").append("{");
        return b.append("}").toString();
    }
}

