// Java class holochain.ActionVerifySignature is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * ------------------------------------------------------------
VerifySignature
 */
public final class ActionVerifySignature implements Seq.Proxy, ArgsAction {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    ActionVerifySignature(Seq.Ref ref) { this.ref = ref; }
    
    public ActionVerifySignature() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped method ActionVerifySignature.Args with unsupported parameter or return types
    
    // skipped method ActionVerifySignature.Do with unsupported parameter or return types
    
    public native String name();
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof ActionVerifySignature)) {
            return false;
        }
        ActionVerifySignature that = (ActionVerifySignature)o;
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("ActionVerifySignature").append("{");
        return b.append("}").toString();
    }
}

