// Java class holochain.AgentEntry is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * AgentEntry structure for building AgentEntryType entries
 */
public final class AgentEntry implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    AgentEntry(Seq.Ref ref) { this.ref = ref; }
    
    public AgentEntry() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field AgentEntry.Identity with unsupported type: *types.Named
    
    public final native byte[] getRevocation();
    public final native void setRevocation(byte[] v);
    
    public final native byte[] getPublicKey();
    public final native void setPublicKey(byte[] v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof AgentEntry)) {
            return false;
        }
        AgentEntry that = (AgentEntry)o;
        // skipped field AgentEntry.Identity with unsupported type: *types.Named
        
        byte[] thisRevocation = getRevocation();
        byte[] thatRevocation = that.getRevocation();
        if (thisRevocation == null) {
            if (thatRevocation != null) {
                return false;
            }
        } else if (!thisRevocation.equals(thatRevocation)) {
            return false;
        }
        byte[] thisPublicKey = getPublicKey();
        byte[] thatPublicKey = that.getPublicKey();
        if (thisPublicKey == null) {
            if (thatPublicKey != null) {
                return false;
            }
        } else if (!thisPublicKey.equals(thatPublicKey)) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getRevocation(), getPublicKey()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("AgentEntry").append("{");
        b.append("Revocation:").append(getRevocation()).append(",");
        b.append("PublicKey:").append(getPublicKey()).append(",");
        return b.append("}").toString();
    }
}

