// Java class holochain.Agent is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * Agent abstracts the key behaviors and connection to a holochain node address
Note that this is currently only a partial abstraction because the NodeID is always a libp2p peer.ID
to complete the abstraction so we could use other libraries for p2p2 network transaction we
would need to also abstract a matching NodeID type
 */
public interface Agent {
    // skipped method Agent.AgentEntry with unsupported parameter or return types
    
    // skipped method Agent.AgentType with unsupported parameter or return types
    
    // skipped method Agent.GenKeys with unsupported parameter or return types
    
    // skipped method Agent.Identity with unsupported parameter or return types
    
    // skipped method Agent.NodeID with unsupported parameter or return types
    
    // skipped method Agent.PrivKey with unsupported parameter or return types
    
    // skipped method Agent.PubKey with unsupported parameter or return types
    
    // skipped method Agent.SetIdentity with unsupported parameter or return types
    
    
}

