// Java class holochain.AppMsg is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class AppMsg implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    AppMsg(Seq.Ref ref) { this.ref = ref; }
    
    public AppMsg() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native String getZomeType();
    public final native void setZomeType(String v);
    
    public final native String getBody();
    public final native void setBody(String v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof AppMsg)) {
            return false;
        }
        AppMsg that = (AppMsg)o;
        String thisZomeType = getZomeType();
        String thatZomeType = that.getZomeType();
        if (thisZomeType == null) {
            if (thatZomeType != null) {
                return false;
            }
        } else if (!thisZomeType.equals(thatZomeType)) {
            return false;
        }
        String thisBody = getBody();
        String thatBody = that.getBody();
        if (thisBody == null) {
            if (thatBody != null) {
                return false;
            }
        } else if (!thisBody.equals(thatBody)) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getZomeType(), getBody()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("AppMsg").append("{");
        b.append("ZomeType:").append(getZomeType()).append(",");
        b.append("Body:").append(getBody()).append(",");
        return b.append("}").toString();
    }
}

