// Java class holochain.AppPackage is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class AppPackage implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    AppPackage(Seq.Ref ref) { this.ref = ref; }
    
    public AppPackage() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native String getVersion();
    public final native void setVersion(String v);
    
    public final native String getGenerator();
    public final native void setGenerator(String v);
    
    // skipped field AppPackage.DNA with unsupported type: *types.Named
    
    // skipped field AppPackage.TestSets with unsupported type: *types.Slice
    
    // skipped field AppPackage.UI with unsupported type: *types.Slice
    
    // skipped field AppPackage.Scenarios with unsupported type: *types.Slice
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof AppPackage)) {
            return false;
        }
        AppPackage that = (AppPackage)o;
        String thisVersion = getVersion();
        String thatVersion = that.getVersion();
        if (thisVersion == null) {
            if (thatVersion != null) {
                return false;
            }
        } else if (!thisVersion.equals(thatVersion)) {
            return false;
        }
        String thisGenerator = getGenerator();
        String thatGenerator = that.getGenerator();
        if (thisGenerator == null) {
            if (thatGenerator != null) {
                return false;
            }
        } else if (!thisGenerator.equals(thatGenerator)) {
            return false;
        }
        // skipped field AppPackage.DNA with unsupported type: *types.Named
        
        // skipped field AppPackage.TestSets with unsupported type: *types.Slice
        
        // skipped field AppPackage.UI with unsupported type: *types.Slice
        
        // skipped field AppPackage.Scenarios with unsupported type: *types.Slice
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getVersion(), getGenerator()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("AppPackage").append("{");
        b.append("Version:").append(getVersion()).append(",");
        b.append("Generator:").append(getGenerator()).append(",");
        return b.append("}").toString();
    }
}

