// Java class holochain.AppPackageTests is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class AppPackageTests implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    AppPackageTests(Seq.Ref ref) { this.ref = ref; }
    
    public AppPackageTests() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native String getName();
    public final native void setName(String v);
    
    // skipped field AppPackageTests.TestSet with unsupported type: *types.Named
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof AppPackageTests)) {
            return false;
        }
        AppPackageTests that = (AppPackageTests)o;
        String thisName = getName();
        String thatName = that.getName();
        if (thisName == null) {
            if (thatName != null) {
                return false;
            }
        } else if (!thisName.equals(thatName)) {
            return false;
        }
        // skipped field AppPackageTests.TestSet with unsupported type: *types.Named
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getName()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("AppPackageTests").append("{");
        b.append("Name:").append(getName()).append(",");
        return b.append("}").toString();
    }
}

