// Java class holochain.ArgsAction is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public interface ArgsAction {
    // skipped method ArgsAction.Args with unsupported parameter or return types
    
    // skipped method ArgsAction.Do with unsupported parameter or return types
    
    
}

