// Java class holochain.ChainPair is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class ChainPair implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    ChainPair(Seq.Ref ref) { this.ref = ref; }
    
    public ChainPair() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native Header getHeader();
    public final native void setHeader(Header v);
    
    public final native Entry getEntry();
    public final native void setEntry(Entry v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof ChainPair)) {
            return false;
        }
        ChainPair that = (ChainPair)o;
        Header thisHeader = getHeader();
        Header thatHeader = that.getHeader();
        if (thisHeader == null) {
            if (thatHeader != null) {
                return false;
            }
        } else if (!thisHeader.equals(thatHeader)) {
            return false;
        }
        Entry thisEntry = getEntry();
        Entry thatEntry = that.getEntry();
        if (thisEntry == null) {
            if (thatEntry != null) {
                return false;
            }
        } else if (!thisEntry.equals(thatEntry)) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getHeader(), getEntry()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("ChainPair").append("{");
        b.append("Header:").append(getHeader()).append(",");
        b.append("Entry:").append(getEntry()).append(",");
        return b.append("}").toString();
    }
}

