// Java class holochain.Change is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * Change represents a semantic change that needs to be reported
 */
public final class Change implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    Change(Seq.Ref ref) { this.ref = ref; }
    
    public Change() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field Change.Type with unsupported type: *types.Named
    
    public final native String getMessage();
    public final native void setMessage(String v);
    
    public final native long getAsOf();
    public final native void setAsOf(long v);
    
    public native void log();
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof Change)) {
            return false;
        }
        Change that = (Change)o;
        // skipped field Change.Type with unsupported type: *types.Named
        
        String thisMessage = getMessage();
        String thatMessage = that.getMessage();
        if (thisMessage == null) {
            if (thatMessage != null) {
                return false;
            }
        } else if (!thisMessage.equals(thatMessage)) {
            return false;
        }
        long thisAsOf = getAsOf();
        long thatAsOf = that.getAsOf();
        if (thisAsOf != thatAsOf) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getMessage(), getAsOf()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("Change").append("{");
        b.append("Message:").append(getMessage()).append(",");
        b.append("AsOf:").append(getAsOf()).append(",");
        return b.append("}").toString();
    }
}

