// Java class holochain.CloneSpec is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class CloneSpec implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    CloneSpec(Seq.Ref ref) { this.ref = ref; }
    
    public CloneSpec() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native String getRole();
    public final native void setRole(String v);
    
    public final native long getNumber();
    public final native void setNumber(long v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof CloneSpec)) {
            return false;
        }
        CloneSpec that = (CloneSpec)o;
        String thisRole = getRole();
        String thatRole = that.getRole();
        if (thisRole == null) {
            if (thatRole != null) {
                return false;
            }
        } else if (!thisRole.equals(thatRole)) {
            return false;
        }
        long thisNumber = getNumber();
        long thatNumber = that.getNumber();
        if (thisNumber != thatNumber) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getRole(), getNumber()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("CloneSpec").append("{");
        b.append("Role:").append(getRole()).append(",");
        b.append("Number:").append(getNumber()).append(",");
        return b.append("}").toString();
    }
}

