// Java class holochain.CloserPeersResp is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class CloserPeersResp implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    CloserPeersResp(Seq.Ref ref) { this.ref = ref; }
    
    public CloserPeersResp() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field CloserPeersResp.CloserPeers with unsupported type: *types.Slice
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof CloserPeersResp)) {
            return false;
        }
        CloserPeersResp that = (CloserPeersResp)o;
        // skipped field CloserPeersResp.CloserPeers with unsupported type: *types.Slice
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("CloserPeersResp").append("{");
        return b.append("}").toString();
    }
}

