// Java class holochain.CommittingAction is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * CommittingAction provides an abstraction for grouping actions which carry Entry data
 */
public interface CommittingAction extends Action, ArgsAction, ValidatingAction {
    // skipped method CommittingAction.Args with unsupported parameter or return types
    
    public void checkValidationRequest(EntryDef def) throws Exception;
    // skipped method CommittingAction.Do with unsupported parameter or return types
    
    public Entry entry();
    public String entryType();
    public String name();
    // skipped method CommittingAction.Receive with unsupported parameter or return types
    
    public void setHeader(Header header);
    // skipped method CommittingAction.SysValidation with unsupported parameter or return types
    
    
}

