// Java class holochain.DHT is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * DHT struct holds the data necessary to run the distributed hash table
 */
public final class DHT implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    /**
     * NewDHT creates a new DHT structure
     */
    public DHT(Holochain_ h) {
        this.ref = __NewDHT(h);
    }
    
    private static native Seq.Ref __NewDHT(Holochain_ h);
    
    DHT(Seq.Ref ref) { this.ref = ref; }
    
    // skipped method DHT.AddGossiper with unsupported parameter or return types
    
    // skipped method DHT.Change with unsupported parameter or return types
    
    /**
     * Close cleans up the DHT
     */
    public native void close();
    // skipped method DHT.DeleteGossiper with unsupported parameter or return types
    
    /**
     * DumpIdx converts message and data of a DHT change request to a string for human consumption
     */
    public native String dumpIdx(long idx) throws Exception;
    /**
     * DumpIdxJSON converts message and data of a DHT change request to a JSON string representation.
     */
    public native String dumpIdxJSON(long idx) throws Exception;
    // skipped method DHT.FindGossiper with unsupported parameter or return types
    
    // skipped method DHT.GetFingerprint with unsupported parameter or return types
    
    // skipped method DHT.GetGossiper with unsupported parameter or return types
    
    /**
     * GetIdx returns the current put index for gossip
     */
    public native long getIdx() throws Exception;
    // skipped method DHT.GetIdxMessage with unsupported parameter or return types
    
    // skipped method DHT.GetPuts with unsupported parameter or return types
    
    /**
     * HandleGossipPuts waits on a channel for gossip changes
     */
    public native void handleGossipPuts() throws Exception;
    /**
     * HandleGossipWiths waits on a channel for gossipWith requests
     */
    public native void handleGossipWiths() throws Exception;
    // skipped method DHT.HaveFingerprint with unsupported parameter or return types
    
    /**
     * JSON converts a DHT into a JSON string representation.
     */
    public native String json() throws Exception;
    // skipped method DHT.Query with unsupported parameter or return types
    
    /**
     * SetupDHT prepares a DHT for use by putting the genesis entries that are added by GenChain
     */
    public native void setupDHT() throws Exception;
    /**
     * Start initiates listening for DHT &amp; Gossip protocol messages on the node
     */
    public native void start() throws Exception;
    /**
     * String converts a DHT into a human readable string
     */
    public native String string();
    // skipped method DHT.UpdateGossiper with unsupported parameter or return types
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof DHT)) {
            return false;
        }
        DHT that = (DHT)o;
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        return string();
    }
}

