// Java class holochain.Entry is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * Entry describes serialization and deserialziation of entry data
 */
public interface Entry {
    // skipped method Entry.Content with unsupported parameter or return types
    
    public byte[] marshal() throws Exception;
    // skipped method Entry.Sum with unsupported parameter or return types
    
    public void unmarshal(byte[] p0) throws Exception;
    
}

