// Java class holochain.EntryDefFile is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class EntryDefFile implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    EntryDefFile(Seq.Ref ref) { this.ref = ref; }
    
    public EntryDefFile() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native String getName();
    public final native void setName(String v);
    
    public final native String getDataFormat();
    public final native void setDataFormat(String v);
    
    public final native String getSchema();
    public final native void setSchema(String v);
    
    public final native String getSchemaFile();
    public final native void setSchemaFile(String v);
    
    public final native String getSharing();
    public final native void setSharing(String v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof EntryDefFile)) {
            return false;
        }
        EntryDefFile that = (EntryDefFile)o;
        String thisName = getName();
        String thatName = that.getName();
        if (thisName == null) {
            if (thatName != null) {
                return false;
            }
        } else if (!thisName.equals(thatName)) {
            return false;
        }
        String thisDataFormat = getDataFormat();
        String thatDataFormat = that.getDataFormat();
        if (thisDataFormat == null) {
            if (thatDataFormat != null) {
                return false;
            }
        } else if (!thisDataFormat.equals(thatDataFormat)) {
            return false;
        }
        String thisSchema = getSchema();
        String thatSchema = that.getSchema();
        if (thisSchema == null) {
            if (thatSchema != null) {
                return false;
            }
        } else if (!thisSchema.equals(thatSchema)) {
            return false;
        }
        String thisSchemaFile = getSchemaFile();
        String thatSchemaFile = that.getSchemaFile();
        if (thisSchemaFile == null) {
            if (thatSchemaFile != null) {
                return false;
            }
        } else if (!thisSchemaFile.equals(thatSchemaFile)) {
            return false;
        }
        String thisSharing = getSharing();
        String thatSharing = that.getSharing();
        if (thisSharing == null) {
            if (thatSharing != null) {
                return false;
            }
        } else if (!thisSharing.equals(thatSharing)) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getName(), getDataFormat(), getSchema(), getSchemaFile(), getSharing()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("EntryDefFile").append("{");
        b.append("Name:").append(getName()).append(",");
        b.append("DataFormat:").append(getDataFormat()).append(",");
        b.append("Schema:").append(getSchema()).append(",");
        b.append("SchemaFile:").append(getSchemaFile()).append(",");
        b.append("Sharing:").append(getSharing()).append(",");
        return b.append("}").toString();
    }
}

