// Java class holochain.FindNodeReq is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class FindNodeReq implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    FindNodeReq(Seq.Ref ref) { this.ref = ref; }
    
    public FindNodeReq() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field FindNodeReq.H with unsupported type: *types.Named
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof FindNodeReq)) {
            return false;
        }
        FindNodeReq that = (FindNodeReq)o;
        // skipped field FindNodeReq.H with unsupported type: *types.Named
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("FindNodeReq").append("{");
        return b.append("}").toString();
    }
}

