// Java class holochain.GetOptions is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * GetOptions options to holochain level Get functions
 */
public final class GetOptions implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    GetOptions(Seq.Ref ref) { this.ref = ref; }
    
    public GetOptions() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native long getStatusMask();
    public final native void setStatusMask(long v);
    
    public final native long getGetMask();
    public final native void setGetMask(long v);
    
    public final native boolean getLocal();
    public final native void setLocal(boolean v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof GetOptions)) {
            return false;
        }
        GetOptions that = (GetOptions)o;
        long thisStatusMask = getStatusMask();
        long thatStatusMask = that.getStatusMask();
        if (thisStatusMask != thatStatusMask) {
            return false;
        }
        long thisGetMask = getGetMask();
        long thatGetMask = that.getGetMask();
        if (thisGetMask != thatGetMask) {
            return false;
        }
        boolean thisLocal = getLocal();
        boolean thatLocal = that.getLocal();
        if (thisLocal != thatLocal) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getStatusMask(), getGetMask(), getLocal()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("GetOptions").append("{");
        b.append("StatusMask:").append(getStatusMask()).append(",");
        b.append("GetMask:").append(getGetMask()).append(",");
        b.append("Local:").append(getLocal()).append(",");
        return b.append("}").toString();
    }
}

