// Java class holochain.GetReq is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * GetReq holds the data of a get request
 */
public final class GetReq implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    GetReq(Seq.Ref ref) { this.ref = ref; }
    
    public GetReq() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field GetReq.H with unsupported type: *types.Named
    
    public final native long getStatusMask();
    public final native void setStatusMask(long v);
    
    public final native long getGetMask();
    public final native void setGetMask(long v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof GetReq)) {
            return false;
        }
        GetReq that = (GetReq)o;
        // skipped field GetReq.H with unsupported type: *types.Named
        
        long thisStatusMask = getStatusMask();
        long thatStatusMask = that.getStatusMask();
        if (thisStatusMask != thatStatusMask) {
            return false;
        }
        long thisGetMask = getGetMask();
        long thatGetMask = that.getGetMask();
        if (thisGetMask != thatGetMask) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getStatusMask(), getGetMask()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("GetReq").append("{");
        b.append("StatusMask:").append(getStatusMask()).append(",");
        b.append("GetMask:").append(getGetMask()).append(",");
        return b.append("}").toString();
    }
}

