// Java class holochain.GossipReq is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * GossipReq holds a gossip request
 */
public final class GossipReq implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    GossipReq(Seq.Ref ref) { this.ref = ref; }
    
    public GossipReq() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native long getMyIdx();
    public final native void setMyIdx(long v);
    
    public final native long getYourIdx();
    public final native void setYourIdx(long v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof GossipReq)) {
            return false;
        }
        GossipReq that = (GossipReq)o;
        long thisMyIdx = getMyIdx();
        long thatMyIdx = that.getMyIdx();
        if (thisMyIdx != thatMyIdx) {
            return false;
        }
        long thisYourIdx = getYourIdx();
        long thatYourIdx = that.getYourIdx();
        if (thisYourIdx != thatYourIdx) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getMyIdx(), getYourIdx()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("GossipReq").append("{");
        b.append("MyIdx:").append(getMyIdx()).append(",");
        b.append("YourIdx:").append(getYourIdx()).append(",");
        return b.append("}").toString();
    }
}

