// Java class holochain.Holochain_ is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class Holochain_ implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    Holochain_(Seq.Ref ref) { this.ref = ref; }
    
    public Holochain_() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field Holochain_.Config with unsupported type: *types.Named
    
    public native void activate() throws Exception;
    // skipped method Holochain_.AddAgentEntry with unsupported parameter or return types
    
    // skipped method Holochain_.AddBridgeAsCallee with unsupported parameter or return types
    
    // skipped method Holochain_.AddBridgeAsCaller with unsupported parameter or return types
    
    // skipped method Holochain_.AddPeer with unsupported parameter or return types
    
    public native Agent agent();
    // skipped method Holochain_.AgentHash with unsupported parameter or return types
    
    // skipped method Holochain_.AgentTopHash with unsupported parameter or return types
    
    public native void bSget() throws Exception;
    public native void bSpost() throws Exception;
    // skipped method Holochain_.BridgeCall with unsupported parameter or return types
    
    public native void buildBridge(BridgeApp app, String port) throws Exception;
    // skipped method Holochain_.Call with unsupported parameter or return types
    
    public native Chain chain();
    public native void close();
    public native String dbPath();
    public native DHT dht();
    // skipped method Holochain_.DNAHash with unsupported parameter or return types
    
    public native String dnaPath();
    public native void debug(String m);
    // skipped method Holochain_.Debugf with unsupported parameter or return types
    
    // skipped method Holochain_.EncodeDNA with unsupported parameter or return types
    
    // skipped method Holochain_.GenChain with unsupported parameter or return types
    
    // skipped method Holochain_.GetBridgeToken with unsupported parameter or return types
    
    // skipped method Holochain_.GetBridges with unsupported parameter or return types
    
    public native EntryDef getEntryDef(String t) throws Exception;
    // skipped method Holochain_.GetPrivateEntryDefs with unsupported parameter or return types
    
    public native String getProperty(String prop) throws Exception;
    // skipped method Holochain_.GetValidationResponse with unsupported parameter or return types
    
    public native Zome getZome(String zName) throws Exception;
    public native Zome getZomeForEntryType(String t) throws Exception;
    public native void handleAsyncSends() throws Exception;
    // skipped method Holochain_.HandlePeerFound with unsupported parameter or return types
    
    // skipped method Holochain_.HashSpec with unsupported parameter or return types
    
    public native Ribosome makeRibosome(String t) throws Exception;
    public native String name();
    // skipped method Holochain_.NewEntry with unsupported parameter or return types
    
    public native Node node();
    public native String nodeIDStr();
    public native Nucleus nucleus();
    public native void prepare() throws Exception;
    public native void prepareHashType() throws Exception;
    // skipped method Holochain_.Query with unsupported parameter or return types
    
    public native void reset() throws Exception;
    public native String rootPath();
    // skipped method Holochain_.Send with unsupported parameter or return types
    
    // skipped method Holochain_.SendAsync with unsupported parameter or return types
    
    public native byte[] sign(byte[] doc) throws Exception;
    public native void startBackgroundTasks();
    public native boolean started();
    // skipped method Holochain_.TaskTicker with unsupported parameter or return types
    
    public native String testPath();
    // skipped method Holochain_.Top with unsupported parameter or return types
    
    public native String uiPath();
    // skipped method Holochain_.ValidateAction with unsupported parameter or return types
    
    // skipped method Holochain_.VerifySignature with unsupported parameter or return types
    
    // skipped method Holochain_.Walk with unsupported parameter or return types
    
    public native String zomePath(Zome z);
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof Holochain_)) {
            return false;
        }
        Holochain_ that = (Holochain_)o;
        // skipped field Holochain_.Config with unsupported type: *types.Named
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("Holochain_").append("{");
        return b.append("}").toString();
    }
}

