// Java class holochain.JSONEntry is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * JSONEntry is a structure for implementing JSON encoding of Entry content
 */
public final class JSONEntry implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    JSONEntry(Seq.Ref ref) { this.ref = ref; }
    
    public JSONEntry() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field JSONEntry.C with unsupported type: *types.Interface
    
    // skipped method JSONEntry.Content with unsupported parameter or return types
    
    public native byte[] marshal() throws Exception;
    public native void unmarshal(byte[] b) throws Exception;
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof JSONEntry)) {
            return false;
        }
        JSONEntry that = (JSONEntry)o;
        // skipped field JSONEntry.C with unsupported type: *types.Interface
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("JSONEntry").append("{");
        return b.append("}").toString();
    }
}

