// Java class holochain.LibP2PAgent is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class LibP2PAgent implements Seq.Proxy, Agent {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    LibP2PAgent(Seq.Ref ref) { this.ref = ref; }
    
    public LibP2PAgent() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped method LibP2PAgent.AgentEntry with unsupported parameter or return types
    
    // skipped method LibP2PAgent.AgentType with unsupported parameter or return types
    
    // skipped method LibP2PAgent.GenKeys with unsupported parameter or return types
    
    // skipped method LibP2PAgent.Identity with unsupported parameter or return types
    
    // skipped method LibP2PAgent.NodeID with unsupported parameter or return types
    
    // skipped method LibP2PAgent.PrivKey with unsupported parameter or return types
    
    // skipped method LibP2PAgent.PubKey with unsupported parameter or return types
    
    // skipped method LibP2PAgent.SetIdentity with unsupported parameter or return types
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof LibP2PAgent)) {
            return false;
        }
        LibP2PAgent that = (LibP2PAgent)o;
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("LibP2PAgent").append("{");
        return b.append("}").toString();
    }
}

