// Java class holochain.LinksEntry is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * LinksEntry holds one or more links
 */
public final class LinksEntry implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    LinksEntry(Seq.Ref ref) { this.ref = ref; }
    
    public LinksEntry() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field LinksEntry.Links with unsupported type: *types.Slice
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof LinksEntry)) {
            return false;
        }
        LinksEntry that = (LinksEntry)o;
        // skipped field LinksEntry.Links with unsupported type: *types.Slice
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("LinksEntry").append("{");
        return b.append("}").toString();
    }
}

