// Java class holochain.LinkReq is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * LinkReq holds a link request
 */
public final class LinkReq implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    LinkReq(Seq.Ref ref) { this.ref = ref; }
    
    public LinkReq() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field LinkReq.Base with unsupported type: *types.Named
    
    // skipped field LinkReq.Links with unsupported type: *types.Named
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof LinkReq)) {
            return false;
        }
        LinkReq that = (LinkReq)o;
        // skipped field LinkReq.Base with unsupported type: *types.Named
        
        // skipped field LinkReq.Links with unsupported type: *types.Named
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("LinkReq").append("{");
        return b.append("}").toString();
    }
}

