// Java class holochain.Logger is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * Logger holds logger configuration
 */
public final class Logger implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    Logger(Seq.Ref ref) { this.ref = ref; }
    
    public Logger() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native String getName();
    public final native void setName(String v);
    
    public final native boolean getEnabled();
    public final native void setEnabled(boolean v);
    
    public final native String getFormat();
    public final native void setFormat(String v);
    
    public final native String getPrefix();
    public final native void setPrefix(String v);
    
    // skipped field Logger.PrefixColor with unsupported type: *types.Pointer
    
    // skipped method Logger.GetColor with unsupported parameter or return types
    
    // skipped method Logger.Log with unsupported parameter or return types
    
    // skipped method Logger.Logf with unsupported parameter or return types
    
    // skipped method Logger.New with unsupported parameter or return types
    
    public native void setPrefix(String prefixFormat);
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof Logger)) {
            return false;
        }
        Logger that = (Logger)o;
        String thisName = getName();
        String thatName = that.getName();
        if (thisName == null) {
            if (thatName != null) {
                return false;
            }
        } else if (!thisName.equals(thatName)) {
            return false;
        }
        boolean thisEnabled = getEnabled();
        boolean thatEnabled = that.getEnabled();
        if (thisEnabled != thatEnabled) {
            return false;
        }
        String thisFormat = getFormat();
        String thatFormat = that.getFormat();
        if (thisFormat == null) {
            if (thatFormat != null) {
                return false;
            }
        } else if (!thisFormat.equals(thatFormat)) {
            return false;
        }
        String thisPrefix = getPrefix();
        String thatPrefix = that.getPrefix();
        if (thisPrefix == null) {
            if (thatPrefix != null) {
                return false;
            }
        } else if (!thisPrefix.equals(thatPrefix)) {
            return false;
        }
        // skipped field Logger.PrefixColor with unsupported type: *types.Pointer
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getName(), getEnabled(), getFormat(), getPrefix()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("Logger").append("{");
        b.append("Name:").append(getName()).append(",");
        b.append("Enabled:").append(getEnabled()).append(",");
        b.append("Format:").append(getFormat()).append(",");
        b.append("Prefix:").append(getPrefix()).append(",");
        return b.append("}").toString();
    }
}

