// Java class holochain.Message is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * Message represents data that can be sent to node in the network
 */
public final class Message implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    Message(Seq.Ref ref) { this.ref = ref; }
    
    public Message() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field Message.Type with unsupported type: *types.Named
    
    // skipped field Message.Time with unsupported type: *types.Named
    
    // skipped field Message.From with unsupported type: *types.Named
    
    // skipped field Message.Body with unsupported type: *types.Interface
    
    // skipped method Message.Decode with unsupported parameter or return types
    
    /**
     * Encode codes a message to gob format
    @TODO generalize for other message encoding formats
     */
    public native byte[] encode() throws Exception;
    // skipped method Message.Fingerprint with unsupported parameter or return types
    
    /**
     * String converts a message to a nice string
     */
    public native String string();
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof Message)) {
            return false;
        }
        Message that = (Message)o;
        // skipped field Message.Type with unsupported type: *types.Named
        
        // skipped field Message.Time with unsupported type: *types.Named
        
        // skipped field Message.From with unsupported type: *types.Named
        
        // skipped field Message.Body with unsupported type: *types.Interface
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        return string();
    }
}

