// Java class holochain.Node is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * Node represents a node in the network
 */
public final class Node implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    /**
     * NewNode creates a new node with given multiAddress listener string and identity
     */
    public Node(String listenAddr, String protoMux, LibP2PAgent agent, boolean enableNATUPnP, Logger log) {
        this.ref = __NewNode(listenAddr, protoMux, agent, enableNATUPnP, log);
    }
    
    private static native Seq.Ref __NewNode(String listenAddr, String protoMux, LibP2PAgent agent, boolean enableNATUPnP, Logger log);
    
    Node(Seq.Ref ref) { this.ref = ref; }
    
    // skipped field Node.HashAddr with unsupported type: *types.Named
    
    // skipped field Node.NetAddr with unsupported type: *types.Named
    
    // skipped method Node.Block with unsupported parameter or return types
    
    /**
     * Close shuts down the node
     */
    public native void close() throws Exception;
    // skipped method Node.Context with unsupported parameter or return types
    
    // skipped method Node.Distance with unsupported parameter or return types
    
    // skipped method Node.EnableMDNSDiscovery with unsupported parameter or return types
    
    // skipped method Node.ExternalAddr with unsupported parameter or return types
    
    // skipped method Node.FindLocal with unsupported parameter or return types
    
    // skipped method Node.FindPeer with unsupported parameter or return types
    
    // skipped method Node.GetClosestPeers with unsupported parameter or return types
    
    // skipped method Node.InitBlockedList with unsupported parameter or return types
    
    // skipped method Node.IsBlocked with unsupported parameter or return types
    
    // skipped method Node.NewMessage with unsupported parameter or return types
    
    // skipped method Node.Process with unsupported parameter or return types
    
    // skipped method Node.Send with unsupported parameter or return types
    
    /**
     * StartProtocol initiates listening for a protocol on the node
     */
    public native void startProtocol(Holochain_ h, long proto) throws Exception;
    // skipped method Node.Unblock with unsupported parameter or return types
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof Node)) {
            return false;
        }
        Node that = (Node)o;
        // skipped field Node.HashAddr with unsupported type: *types.Named
        
        // skipped field Node.NetAddr with unsupported type: *types.Named
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("Node").append("{");
        return b.append("}").toString();
    }
}

