// Java class holochain.Package is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * Package holds app specified data needed for validation (wire package)
 */
public final class Package implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    Package(Seq.Ref ref) { this.ref = ref; }
    
    public Package() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native byte[] getChain();
    public final native void setChain(byte[] v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof Package)) {
            return false;
        }
        Package that = (Package)o;
        byte[] thisChain = getChain();
        byte[] thatChain = that.getChain();
        if (thisChain == null) {
            if (thatChain != null) {
                return false;
            }
        } else if (!thisChain.equals(thatChain)) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getChain()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("Package").append("{");
        b.append("Chain:").append(getChain()).append(",");
        return b.append("}").toString();
    }
}

