// Java class holochain.PeerRecord is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class PeerRecord implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    PeerRecord(Seq.Ref ref) { this.ref = ref; }
    
    public PeerRecord() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field PeerRecord.ID with unsupported type: *types.Named
    
    public final native String getWarrant();
    public final native void setWarrant(String v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof PeerRecord)) {
            return false;
        }
        PeerRecord that = (PeerRecord)o;
        // skipped field PeerRecord.ID with unsupported type: *types.Named
        
        String thisWarrant = getWarrant();
        String thatWarrant = that.getWarrant();
        if (thisWarrant == null) {
            if (thatWarrant != null) {
                return false;
            }
        } else if (!thisWarrant.equals(thatWarrant)) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getWarrant()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("PeerRecord").append("{");
        b.append("Warrant:").append(getWarrant()).append(",");
        return b.append("}").toString();
    }
}

