// Java class holochain.PeerInfo is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * an encodable version of pstore.PeerInfo which gob doesn&#39;t like
also libp2p encodes other stuff like connection type into this
which we may have to do too.
 */
public final class PeerInfo implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    PeerInfo(Seq.Ref ref) { this.ref = ref; }
    
    public PeerInfo() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native byte[] getID();
    public final native void setID(byte[] v);
    
    // skipped field PeerInfo.Addrs with unsupported type: *types.Slice
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof PeerInfo)) {
            return false;
        }
        PeerInfo that = (PeerInfo)o;
        byte[] thisID = getID();
        byte[] thatID = that.getID();
        if (thisID == null) {
            if (thatID != null) {
                return false;
            }
        } else if (!thisID.equals(thatID)) {
            return false;
        }
        // skipped field PeerInfo.Addrs with unsupported type: *types.Slice
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getID()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("PeerInfo").append("{");
        b.append("ID:").append(getID()).append(",");
        return b.append("}").toString();
    }
}

