// Java class holochain.Progenitor is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * Progenitor holds data on the creator of the DNA
 */
public final class Progenitor implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    Progenitor(Seq.Ref ref) { this.ref = ref; }
    
    public Progenitor() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native String getIdentity();
    public final native void setIdentity(String v);
    
    public final native byte[] getPubKey();
    public final native void setPubKey(byte[] v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof Progenitor)) {
            return false;
        }
        Progenitor that = (Progenitor)o;
        String thisIdentity = getIdentity();
        String thatIdentity = that.getIdentity();
        if (thisIdentity == null) {
            if (thatIdentity != null) {
                return false;
            }
        } else if (!thisIdentity.equals(thatIdentity)) {
            return false;
        }
        byte[] thisPubKey = getPubKey();
        byte[] thatPubKey = that.getPubKey();
        if (thisPubKey == null) {
            if (thatPubKey != null) {
                return false;
            }
        } else if (!thisPubKey.equals(thatPubKey)) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getIdentity(), getPubKey()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("Progenitor").append("{");
        b.append("Identity:").append(getIdentity()).append(",");
        b.append("PubKey:").append(getPubKey()).append(",");
        return b.append("}").toString();
    }
}

