// Java class holochain.Put is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * Put holds a put or link for gossiping
 */
public final class Put implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    Put(Seq.Ref ref) { this.ref = ref; }
    
    public Put() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native long getIdx();
    public final native void setIdx(long v);
    
    // skipped field Put.M with unsupported type: *types.Named
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof Put)) {
            return false;
        }
        Put that = (Put)o;
        long thisIdx = getIdx();
        long thatIdx = that.getIdx();
        if (thisIdx != thatIdx) {
            return false;
        }
        // skipped field Put.M with unsupported type: *types.Named
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getIdx()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("Put").append("{");
        b.append("Idx:").append(getIdx()).append(",");
        return b.append("}").toString();
    }
}

