// Java class holochain.QueryOrder is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class QueryOrder implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    QueryOrder(Seq.Ref ref) { this.ref = ref; }
    
    public QueryOrder() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native boolean getAscending();
    public final native void setAscending(boolean v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof QueryOrder)) {
            return false;
        }
        QueryOrder that = (QueryOrder)o;
        boolean thisAscending = getAscending();
        boolean thatAscending = that.getAscending();
        if (thisAscending != thatAscending) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getAscending()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("QueryOrder").append("{");
        b.append("Ascending:").append(getAscending()).append(",");
        return b.append("}").toString();
    }
}

