// Java class holochain.Revocation is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public interface Revocation {
    public byte[] marshal() throws Exception;
    public void unmarshal(byte[] p0) throws Exception;
    public void verify() throws Exception;
    
}

