// Java class holochain.SchemaValidator is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * SchemaValidator interface for schema validation
 */
public interface SchemaValidator {
    // skipped method SchemaValidator.Validate with unsupported parameter or return types
    
    
}

