// Java class holochain.SelfRevocationWarrant is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * SelfRevocationWarrant warrants that the first party revoked its own key in favor of the second
 */
public final class SelfRevocationWarrant implements Seq.Proxy, Warrant {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    public SelfRevocationWarrant(SelfRevocation revocation) {
        this.ref = __NewSelfRevocationWarrant(revocation);
    }
    
    private static native Seq.Ref __NewSelfRevocationWarrant(SelfRevocation revocation);
    
    SelfRevocationWarrant(Seq.Ref ref) { this.ref = ref; }
    
    // skipped field SelfRevocationWarrant.Revocation with unsupported type: *types.Named
    
    public native void decode(byte[] data) throws Exception;
    public native byte[] encode() throws Exception;
    // skipped method SelfRevocationWarrant.Parties with unsupported parameter or return types
    
    // skipped method SelfRevocationWarrant.Property with unsupported parameter or return types
    
    public native long type();
    public native void verify(Holochain_ h) throws Exception;
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof SelfRevocationWarrant)) {
            return false;
        }
        SelfRevocationWarrant that = (SelfRevocationWarrant)o;
        // skipped field SelfRevocationWarrant.Revocation with unsupported type: *types.Named
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("SelfRevocationWarrant").append("{");
        return b.append("}").toString();
    }
}

