// Java class holochain.SendOptions is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

public final class SendOptions implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    SendOptions(Seq.Ref ref) { this.ref = ref; }
    
    public SendOptions() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native Callback getCallback();
    public final native void setCallback(Callback v);
    
    public final native long getTimeout();
    public final native void setTimeout(long v);
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof SendOptions)) {
            return false;
        }
        SendOptions that = (SendOptions)o;
        Callback thisCallback = getCallback();
        Callback thatCallback = that.getCallback();
        if (thisCallback == null) {
            if (thatCallback != null) {
                return false;
            }
        } else if (!thisCallback.equals(thatCallback)) {
            return false;
        }
        long thisTimeout = getTimeout();
        long thatTimeout = that.getTimeout();
        if (thisTimeout != thatTimeout) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getCallback(), getTimeout()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("SendOptions").append("{");
        b.append("Callback:").append(getCallback()).append(",");
        b.append("Timeout:").append(getTimeout()).append(",");
        return b.append("}").toString();
    }
}

