// Java class holochain.StatusChange is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * StatusChange records change of status of an entry in the header
 */
public final class StatusChange implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    StatusChange(Seq.Ref ref) { this.ref = ref; }
    
    public StatusChange() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native String getAction();
    public final native void setAction(String v);
    
    // skipped field StatusChange.Hash with unsupported type: *types.Named
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof StatusChange)) {
            return false;
        }
        StatusChange that = (StatusChange)o;
        String thisAction = getAction();
        String thatAction = that.getAction();
        if (thisAction == null) {
            if (thatAction != null) {
                return false;
            }
        } else if (!thisAction.equals(thatAction)) {
            return false;
        }
        // skipped field StatusChange.Hash with unsupported type: *types.Named
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getAction()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("StatusChange").append("{");
        b.append("Action:").append(getAction()).append(",");
        return b.append("}").toString();
    }
}

