// Java class holochain.TestFixtures is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * TestFixtures defines data needed to run tests
 */
public final class TestFixtures implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    TestFixtures(Seq.Ref ref) { this.ref = ref; }
    
    public TestFixtures() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped field TestFixtures.Agents with unsupported type: *types.Slice
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof TestFixtures)) {
            return false;
        }
        TestFixtures that = (TestFixtures)o;
        // skipped field TestFixtures.Agents with unsupported type: *types.Slice
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("TestFixtures").append("{");
        return b.append("}").toString();
    }
}

