// Java class holochain.ValidatingAction is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * ValidatingAction provides an abstraction for grouping all the actions that participate in validation loop
 */
public interface ValidatingAction extends Action, ArgsAction {
    // skipped method ValidatingAction.Args with unsupported parameter or return types
    
    public void checkValidationRequest(EntryDef def) throws Exception;
    // skipped method ValidatingAction.Do with unsupported parameter or return types
    
    public String name();
    // skipped method ValidatingAction.Receive with unsupported parameter or return types
    
    // skipped method ValidatingAction.SysValidation with unsupported parameter or return types
    
    
}

