// Java class holochain.ValidateResponse is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * ValidateResponse holds the response to committing validates (PUT/MOD/DEL)
 */
public final class ValidateResponse implements Seq.Proxy {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    ValidateResponse(Seq.Ref ref) { this.ref = ref; }
    
    public ValidateResponse() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native String getType();
    public final native void setType(String v);
    
    // skipped field ValidateResponse.Header with unsupported type: *types.Named
    
    // skipped field ValidateResponse.Entry with unsupported type: *types.Named
    
    // skipped field ValidateResponse.Package with unsupported type: *types.Named
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof ValidateResponse)) {
            return false;
        }
        ValidateResponse that = (ValidateResponse)o;
        String thisType = getType();
        String thatType = that.getType();
        if (thisType == null) {
            if (thatType != null) {
                return false;
            }
        } else if (!thisType.equals(thatType)) {
            return false;
        }
        // skipped field ValidateResponse.Header with unsupported type: *types.Named
        
        // skipped field ValidateResponse.Entry with unsupported type: *types.Named
        
        // skipped field ValidateResponse.Package with unsupported type: *types.Named
        
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getType()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("ValidateResponse").append("{");
        b.append("Type:").append(getType()).append(",");
        return b.append("}").toString();
    }
}

