// Java class holochain.ZygoRibosome is a proxy for talking to a Go program.
//   gobind -lang=java github.com/Holochain/holochain-proto
//
// File is generated by gobind. Do not edit.
package holochain;

import go.Seq;

/**
 * ZygoRibosome holds data needed for the Zygo VM
 */
public final class ZygoRibosome implements Seq.Proxy, Ribosome {
    static { Holochain.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    ZygoRibosome(Seq.Ref ref) { this.ref = ref; }
    
    public ZygoRibosome() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    // skipped method ZygoRibosome.BridgeGenesis with unsupported parameter or return types
    
    // skipped method ZygoRibosome.Call with unsupported parameter or return types
    
    /**
     * ChainGenesis runs the application genesis function
    this function gets called after the genesis entries are added to the chain
     */
    public native void chainGenesis() throws Exception;
    /**
     * Receive calls the app receive function for node-to-node messages
     */
    public native String receive(String from, String msg) throws Exception;
    // skipped method ZygoRibosome.Run with unsupported parameter or return types
    
    // skipped method ZygoRibosome.RunAsyncSendResponse with unsupported parameter or return types
    
    /**
     * Type returns the string value under which this ribosome is registered
     */
    public native String type();
    // skipped method ZygoRibosome.ValidateAction with unsupported parameter or return types
    
    // skipped method ZygoRibosome.ValidatePackagingRequest with unsupported parameter or return types
    
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof ZygoRibosome)) {
            return false;
        }
        ZygoRibosome that = (ZygoRibosome)o;
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("ZygoRibosome").append("{");
        return b.append("}").toString();
    }
}

